apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-nodeport
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      nodePort: {{ .Values.app.nodePort }}
      protocol: TCP
  selector:
    app: {{ .Values.app.name }}